package com.hacktics.diviner.gui.scanwizard;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import com.hacktics.diviner.analyze.AnalyzerUtils;

/**
 * 
 * @author Eran Tamari
 *
 */

public class ReplayTabContent extends GenericTabContent implements ActionListener{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private static final String HEADLINE =  "CSRF Tokens and Required Dynamic Parameters:";
	private static final String DESCRIPTION =  "<html><b>The required dynamic parameters are generated by the application and usually required during the session or the following request.<br>Such values include anti-CSRF tokens and state related values.<br>" +
												"The \"Per Page\" tokens are referring to parameters that may have different values for different pages, such as viewstate, eventtarget, etc.<br>" +
												"The \"Per Session\" tokens are referring to parameters that normally have the same value across different pages in the same session.</b></html>";
	private CsrfTable table;
	public ReplayTabContent(String backButtonCommand, JPanel panel, ActionListener eventHandler)
	{
		super(backButtonCommand, HEADLINE, new JLabel(DESCRIPTION),  panel,  eventHandler);

		panel.setLayout(new BorderLayout(5, 5));

		table = new CsrfTable();

		JButton buttonAddRow = new JButton("Add Token");
		buttonAddRow.addActionListener(this);
		table.setPreferredScrollableViewportSize(new Dimension(500, 70));
		table.setFillsViewportHeight(true);

		//Create the scroll pane and add the table to it.
		JScrollPane scrollPane = new JScrollPane(table);
		panel.add(scrollPane, BorderLayout.CENTER);
		panel.add(buttonAddRow, BorderLayout.PAGE_START);
	}
	
	public void setSelectedCsrfTokens() {
		AnalyzerUtils.setCsrfTokens(table.getTokens());	
	}

	@Override
	public void actionPerformed(ActionEvent arg0) {
		table.addRow();		
	}

}